### PR TITLE
Node JS not installed error Fixed

### PR DESCRIPTION
**Pull request by codGmer**
Node JS not installed error Fixed

### CODE REVIEW

**Review by FrostySo — APPROVED** [review]
Great work! Thanks for your help

**Review by FrostySo — COMMENTED** [review]
Hard to say if this is malicious or not, therefore I will have to update it myself. I hope you understand

**Review by FrostySo — APPROVED** [review]

**Comment by codGmer** [comment]
It's not malicious but good that you updated it yourself, glad to help.

**Comment by kostaslgr7** [comment]
Hello, I am having the same issue, although nodejs and http-server is confirmed installed and working, I get the NodeJs is not installed error.

**Pull request merged**
